version: '3'
services:
  api:
    container_name: api
    image: tilersmyth/deploy-app
    build: .
    restart: always
    env_file:
      - ../production.env
    networks:
      - webnet
    depends_on:
      - db
      - redis
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    networks:
      - webnet
    depends_on:
      - api
  db:
    image: 'postgres:11.5-alpine'
    networks:
      - webnet
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=deploy,deploy_test
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - webnet
    ports:
      - '6379:6379'
networks:
  webnet:
volumes:
  dbdata:
