version: '3'
services:
  app:
    container_name: deploy-app
    restart: always
    build: .
    ports:
      - '80:${PORT}'
    env_file:
      - production.env
    networks:
      - webnet
    depends_on:
      - 'db'
      - 'redis'
  db:
    image: 'postgres:11.5-alpine'
    networks:
      - webnet
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=deploy,deploy_test
    ports:
      - '5432:5432'
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - webnet
    ports:
      - '6379:6379'
networks:
  webnet:
volumes:
  dbdata:
