version: '3'
services:
  db:
    image: 'postgres:11.5-alpine'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=deploy,deploy_test
    ports:
      - '5432:5432'
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
volumes:
  dbdata:
