version: '3'
services:
  db:
    image: 'postgres:11.0-alpine'
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
volumes:
  dbdata:
