name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PW }}
      - name: Build Docker image
        run: docker build -t $REPO:latest .
      - name: Publish Docker image
        run: docker push $REPO
