name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      ID: ${{ secrets.DOCKER_ID }}
      PW: ${{ secrets.DOCKER_PW }}
    steps:
      - uses: actions/checkout@v2
      - name: ORIGINAL VERSION
        run: echo $GITHUB_REF
      - name: REGEXED
        run: echo ${GITHUB_REF#*@}
