name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: |
          cd packages/api 
          yarn run test

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      ID: ${{ secrets.DOCKER_ID }}
      PW: ${{ secrets.DOCKER_PW }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u $ID -p $PW
      - name: Build Docker image
        run: |
          cd packages/api 
          docker build -t $REPO:${GITHUB_REF#*@} .
      - name: Publish Docker image
        run: docker push $REPO:${GITHUB_REF#*@}
