name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: cd packages/api

      - name: Update core files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          rm: true
          source: "./packages/api/deploy"
          target: "app"
          strip_components: 4

      - name: Deploy
        run: ls
