name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd packages/api
      - run: yarn install
      - run: yarn test
