name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.2
      - run: |
          cd packages/api
          yarn run test
