name: api-deploy

on:
  push:
    tags:
      - "api*"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd packages/api
      - name: Update core files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./packages/api/Dockerfile,./packages/api/docker-compose.yml,./packages/api/pg-scripts,./packages/api/production.env,./packages/api/nginx"
          target: "."
          strip_components: 3
          overwrite: true
